### ISSUE TITLE
Add name functionality

### ISSUE THREAD

**Issue by kishlaykiku** [kishlaykiku/stupid-dice-game#2]
- [x] Add name
- [x] Clear text field after clicking ✅
- [x] Keep the label above input field when focused out of the text field

**Comment by kikutestground** [comment]
I would like to work on this issue. **Please assign to me**.

**Comment by kishlaykiku** [comment]
> I would like to work on this issue. **Please assign to me**.

Sure

**Comment by Muhammad-Awab** [comment]
I would like to work on this issue. Please assign to me .

**Comment by kishlaykiku** [comment]
> I would like to work on this issue. Please assign to me .

@Muhammad-Awab Issue has been resolved by @kikutestground
