### ISSUE TITLE
Add CSS animations

### ISSUE THREAD

**Issue by kishlaykiku** [kishlaykiku/stupid-dice-game#4]
**Add animations to the input field**

- [ ] Create a label and make it appear as placeholder after focusing in the input field. After typing a single text and beyond, make the label disappear.
- [ ] Refactor the CSS file
- [ ] Add winner's name (also set max length of names to 10) after fetching from player's name.

**Comment by kikutestground** [comment]
Please assign it to me.

**Comment by kishlaykiku** [comment]
Requirements fullfilled by @kikutestground. Closing Issue.
